bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('customer/', views.customer_index, name='customer'),
    path('customer_account_details/<account_pk>/', views.customer_account_details,
         name='customer_account_details'),
    path('customer_make_transfer/', views.customer_make_transfer,
         name="customer_make_transfer"),
    path('staff/', views.staff_index, name='staff'),
    path('staff_customer_details/<customer_pk>/', views.staff_customer_details,
         name='staff_customer_details')
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    path('accounts/',include('login_app.urls'))
]

bank_app/models.py
from django.db import models, transaction
from decimal import Decimal
from django.db.models import Sum
from django.contrib.auth.models import User
from uuid import uuid4
from django.conf import settings


class Rank(models.Model):
    name = models.CharField(max_length=20)
    value = models.IntegerField(unique=True)

    @classmethod
    def default_rank(cls):
        min_rank = cls.objects.all().aggregate(
            models.Min('value'))['value__min']
        return cls.objects.get(value=min_rank)

    def __str__(self):
        return f"{self.name}"


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.ForeignKey(Rank, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)

    @classmethod
    def create_customer(cls, username, password, email, phone_number, rank=Rank.default_rank()):
        user = User.objects.create_user(
            username=username, password=password, email=email)
        cls(user=user, rank=rank, phone_number=phone_number).save()
        Account(user=user, name='Default Account').save()
        return user

    @property
    def accounts(self):
        return Account.objects.filter(user=self.user)

    @property
    def can_make_loan(self):
        if self.rank.name == 'Basic':
            return False
        else:
            return True

    def __str__(self):
        return f"{self.user} - {self.rank} - {self.phone_number} - {self.pk}"


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=35, unique=False)
    is_loan = models.BooleanField(default=False)

    @classmethod
    def create_account(cls, user, name):
        cls(user=user, name=name).save()

    @property
    def balance(self):
        return Ledger.objects.filter(account=self.pk).aggregate(models.Sum('amount'))['amount__sum'] or Decimal('0')

    @property
    def movements(self):
        return Ledger.objects.filter(account=self.pk)

    def __str__(self):
        return f"{self.pk} - {self.user} - {self.name}"


class Ledger(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=35)

    @classmethod
    def transfer(cls, amount, from_account, to_account, text):
        with transaction.atomic():
            if not from_account.is_loan:
                transaction_id = str(uuid4())
                cls(account=from_account, transaction_id=transaction_id,
                    amount=-amount, text=text).save()
                cls(account=to_account, transaction_id=transaction_id,
                    amount=amount, text=text).save()
            else:
                print('cannot make transfer')

    def __str__(self):
        return f'{self.amount} - {self.transaction_id} - {self.account} - {self.text}'

bank_app/views.py
from django.shortcuts import render, reverse, get_object_or_404
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from .models import Customer, Rank, Account, Ledger
from django.http import HttpResponse
from django.contrib import messages

# from django.contrib.auth.decorators import login_required


def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff'))
    else:
        return HttpResponseRedirect(reverse('bank_app:customer'))


def customer_index(request):
    assert not request.user.is_staff, 'return to staff page'
    customer = request.user.customer
    context = {
        'customer': customer
    }
    return render(request, 'bank_app/customer_index.html', context)


def customer_account_details(request, account_pk):
    assert not request.user.is_staff, 'return to staff page'
    account = get_object_or_404(Account, user=request.user, pk=account_pk)
    context = {
        'account': account,
    }
    return render(request, 'bank_app/customer_account_details.html', context)


def customer_make_transfer(request):
    assert not request.user.is_staff, 'return to staff page'
    if request.method == 'POST':
        amount = Decimal(request.POST['amount'])
        from_account = get_object_or_404(
            Account, pk=request.POST['from_account'])
        to_account = get_object_or_404(Account, pk=request.POST['to_account'])
        text = request.POST['text']
        Ledger.transfer(amount, from_account, to_account, text)
        messages.success(request, 'Transfer successful')
        return HttpResponseRedirect(reverse('bank_app:customer_make_transfer'))

    context = {
        'customer_accounts': request.user.customer.accounts.filter(is_loan=False),
        'all_accounts': Account.objects.all(),
    }
    return render(request, 'bank_app/customer_make_transfer.html', context)


def staff_index(request):
    assert request.user.is_staff, 'return to customer page'
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        phone_number = request.POST['phone_number']
        if password == confirm_password:
            Customer.create_customer(username, password, email, phone_number)
            messages.success(request, 'Customer created')
            return HttpResponseRedirect(reverse('bank_app:staff'))
    context = {
        'ranks': Rank.objects.all(),
        # .order_by('username')
        'all_customers': User.objects.filter(is_staff=False)
    }
    return render(request, 'bank_app/staff_index.html', context)


def staff_customer_details(request, customer_pk):
    assert request.user.is_staff, 'return to customer page'
    if request.method == "POST" and "name" in request.POST:
        name = request.POST['name']
        user = get_object_or_404(User, pk=customer_pk)
        Account.create_account(user, name)
        messages.success(request, 'Account created')
        return HttpResponseRedirect(reverse('bank_app:staff_customer_details', args=(customer_pk)))

    if request.method == 'POST' and 'rank' in request.POST:
        rank = get_object_or_404(Rank, pk=request.POST['rank'])
        customer = get_object_or_404(Customer, user=customer_pk)
        customer.rank = rank
        customer.save()

    customer = get_object_or_404(User, pk=customer_pk)
    context = {
        'ranks': Rank.objects.all(),
        'customer': customer,
    }

    return render(request, 'bank_app/staff_customer_details.html', context)

bank_app/templates/bank_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bank_app/bank_app.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>{%block title%}{%endblock%}</title>
</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

bank_app/templates/bank_app/customer_account_details.html
{% extends "bank_app/base.html" %}

{% block content %}
{% include 'header/customer_header.html' %}
<h2>Account details</h2>
<p>Account name: {{ account.name }}</p>
<p>Account balance: {{ account.balance }}</p>
<hr>
<h4>Movement history</h4>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Text</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
        </tr>
    </thead>
    <tbody>
        {% for movement in account.movements reversed %}
        <tr>
            <td>{{movement.text}}</td>
            <!-- redirect to customer account details -->
            <td>{{ movement.amount }}</td>
            <td>{{ movement.timestamp }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

bank_app/templates/bank_app/customer_index.html
{% extends "bank_app/base.html" %}


{% block content %}
{% include 'header/customer_header.html' %}
<h2>Customer information</h2>
<p>Rank: {{ customer.rank }}</p>
<p>Eligible to make a loan:
    {% if customer.can_make_loan %}
    Yes
    {% else %}
    No
    {% endif %}
</p>

<h2>Your overview</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Account Name</th>
            <th scope="col">Account Balance</th>
        </tr>
    </thead>
    <tbody>
        {% for account in customer.accounts %}
        <tr>

            <td> <a href="{% url 'bank_app:customer_account_details' account.pk %}">{{account.name}}</a></td>
            <!-- redirect to customer account details -->
            <td>{{ account.balance }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

bank_app/templates/bank_app/customer_make_transfer.html
{% extends "bank_app/base.html" %}

{% block content %}
{% include 'header/customer_header.html' %}
<div class="d-flex justify-content-center">
    <h2>Transfer from your account</h2>
</div>
<div class="d-flex justify-content-center">
    {% if messages %}
    <div>
        {% for message in messages %}
        <p {% if message.tags %} class=" {{message.tags}}" {% endif %}>{{message}}</p>
        {% endfor %}
    </div>
    {% endif %}
</div>
<form action="{% url 'bank_app:customer_make_transfer' %}" method="POST">
    {% csrf_token %}
    <div class=" row">
        <div class="col d-flex justify-content-end">
            <label for="amount">Amount</label>
        </div>
        <div class="col">
            <input type="number" name="amount" placeholder="Write the amount">
            <span>kr</span>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-end">
            <label for="from_account">Select your account</label>
        </div>
        <div class="col">
            <select name="from_account">
                {% for account in customer_accounts %}
                <option value="{{ account.pk }}">{{account.name}}</option>
                {% endfor %}
            </select>
        </div>

    </div>
    <div class="row">
        <div class="col d-flex justify-content-end">
            <label for="to_account">Select debit account</label>
        </div>
        <div class="col">
            <select name="to_account" id="">
                {% for account in all_accounts %}
                <option value="{{ account.pk }}">{{ account.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-end"> <label for="text">Text for debit account</label></div>
        <div class="col"><input type="text" name="text" placeholder="Write text for account"></div>

    </div>
    <div class="row">
        <div class="col d-flex justify-content-end">
            <p>
                <input type="checkbox" id="accept" name="accept" value="Terms">
                <label for="accept">Accept <a href="#">Terms & Conditions</a></label>
            </p>
        </div>
        <div class="col">
            <button type="submit">Make Transfer</button>
        </div>
    </div>

</form>

{% endblock %}

bank_app/templates/bank_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_app/login_app.css' %}" />
    <title>BankApp</title>
</head>

<body>
    <h1></h1>
</body>

</html>

bank_app/templates/bank_app/staff_customer_details.html
{% extends "bank_app/base.html" %}

{% block content %}
{% include 'header/staff_header.html' %}
<h4>Details for {{customer.username}}</h4>
<p>Phone number: {{customer.customer.phone_number}}</p>
<p>Can make loan:
    {% if customer.customer.can_make_loan %}
    Yes
    {% else %}
    No
    {% endif %} </p>
<p>Rank: {{ customer.customer.rank }}</p>

<form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="POST">
    {% csrf_token %}
    <label for="ranks">Assign different Rank:</label>
    <select name="rank" id="rank">
        <option value="" disabled selected>Rank</option>
        {% for rank in ranks %}
        <option value="{{ rank.pk }}">{{ rank.name }}</option>
        {% endfor %}
    </select>
    <button type="submit">Update rank</button>
</form>

<hr>

<div class="container">
    <div class="row">
        <div class="col">
            <h5>Add Account for {{ customer.username }}</h5>
            <form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="POST">
                {% csrf_token %}
                <input type="text" id="name" name="name" placeholder="Write account name">
                <button type="submit">Create account</button>
            </form>
            {% if messages %}
            <div>
                {% for message in messages %}
                <p {% if message.tags %} class=" {{message.tags}}" {% endif %}>{{message}}</p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Account Name</th>
                        <th scope="col">Account Balance</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in customer.customer.accounts %}
                    <tr>
                        <td>{{account.name}}</td>
                        <!-- redirect to customer account details -->
                        <td>{{ account.balance }}</td>

                    </tr>
                    {% endfor %}
                </tbody>
        </div>
    </div>
</div>




{% endblock %}

bank_app/templates/bank_app/staff_index.html
{% extends "bank_app/base.html" %}


{% block content %}
{% include 'header/staff_header.html' %}
<div class="container">
    <div class="row">
        <div class="col">
            <h2>Create customer</h2>
            <div>
                <form action="{% url 'bank_app:staff' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" class="form-control mb-3" name="username" placeholder="Username">
                    <input type="text" class="form-control mb-3" name="email" placeholder="Email">
                    <input type="text" class="form-control mb-3" name="phone_number" placeholder="Phone number">
                    <input type="password" class="form-control mb-3" name="password" placeholder="Password">
                    <input type="password" class="form-control mb-3" name="confirm_password" placeholder="Password">
                    <button type="submit">Create customer</button>
                </form>
                {% if messages %}
                <div>
                    {% for message in messages %}
                    <p {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col">
            <h2>List of Customers</h2>

            {% for customer in all_customers %}
            <div class="card p-4 mb-3" style="width: 20rem;">
                <!--add link to customer details -->
                <a href="{% url 'bank_app:staff_customer_details' customer.pk %}">
                    <h5 class="card-title">{{ customer.username }}</h5>
                    <p>Phone number: {{ customer.customer.phone_number }}</p>
                    <p>Rank: {{ customer.customer.rank }}</p>
                </a>
            </div>
            {% endfor %}


        </div>
    </div>
</div>
{% endblock %}